use crate::dirs::Dirs;


pub const TESTS: &'static [&'static str] = &[
    "0.void.dart",
    "1.hello.dart",
    "2.variable.dart",
    "3.addition.dart",
    "4.subtraction.dart",
    "5.multiplication.dart",
    "6.division.dart",
    "7.funcall.dart",
    "8.argpass.dart",
    "9.evaled_argpass.dart",
    "10.arithmetic.dart",
    "11.conditional.dart",
    "12.conditional2.dart",
    "13.conditional3.dart",
    "14.conditional4.dart",
    "15.conditional5.dart",
    "16.mutate.dart",
    "17.mutate_self.dart",
    "18.post_increment.dart",
    "19.post_decrement.dart",
    "20.pre_increment.dart",
    "21.pre_decrement.dart",
    "22.returnvalue.dart",
    "23.logical_or.dart",
    "24.logical_and.dart",
    "25.logical_expr.dart",
    "26.less_than.dart",
    "27.greater_than.dart",
    "28.less_or_equal.dart",
    "29.greater_or_equal.dart",
    "30.equality.dart",
    "31.equality2.dart",
    "32.equality3.dart",
    "33.recursion.dart",
    "34.unary_minus.dart",
    "35.arg_expression.dart",
    "36.arg_expression2.dart",
    "37.arg_expression3.dart",
    "38.arg_expression4.dart",
    "39.not.dart",
    "40.fibonacci.dart",
    "41.difficult_return.dart",
    "42.bitand.dart",
    "43.bitor.dart",
    "44.bitxor.dart",
    "45.left_associative_sum.dart",
    "46.hard_expression.dart",
    "47.left_associative_product.dart",
    "48.string_concat.dart",
    "49.lexical_scope.dart",
    "50.method_reading_field.dart",
    "51.constructor_setting_field.dart",
    "52.constructor_setting_field_from_arg.dart",
    "53.method_postincrementing_field.dart",
    "54.method_postdecrementing_field.dart",
    "55.method_preincrementing_field.dart",
    "56.method_predecrementing_field.dart",
    "57.string_interpolation.dart",
    "58.string_interpolation2.dart",
    "59.string_interpolation3.dart",
    "60.string_interpolation4.dart",
    "61.semicolon_king.dart",
    "62.while.dart",
    "63.dowhile.dart",
    "64.for.dart",
    "65.for2.dart",
    "66.this_constructor_arg.dart",
    "67.access_object_field.dart",
    "68.chained_access.dart",
    "69.chained_methods.dart",
    "70.nested_function.dart",
    "71.nested_functions.dart",
    "72.bodyless_constructor.dart",
    "73.implicit_constructor.dart",
    "74.external_setget.dart",
    "75.external_setget2.dart",
    "76.change_field_instance.dart",
    "77.shadow_field.dart",
    "78.busy_garbageman.dart",
    "79.string_interpolation_with_dot.dart",
    "80.read_file_as_string.dart",
    "81.list_add_element.dart",
    "82.list_clear.dart",
    "83.list_remove_last.dart",
    "84.list_forloop.dart",
    "85.while_counter.dart",
    "86.forloop_counter.dart",
    "87.random_int.dart",
    "88.random_bool.dart",
    "89.random_double.dart",
    "90.toplevel_var.dart",
    "91.toplevel_var_set.dart",
    "92.multifile/main.dart",
    "93.external_constructor/main.dart",
    "94.shaded_topvar/main.dart",
    "95.const_topvar.dart",
    "96.list_access_index.dart",
    "97.list_access_index2.dart",
    "98.chained_index.dart",
    "99.lookup.dart",
    "100.this_params_overrides_fields.dart",
    "101.inherit_methods.dart",
    "102.list_set_by_index.dart",
    "103.list_set_by_index2.dart",
    "104.list_set_by_index3.dart",
    "105.calling_into_list_of_objects.dart",
    "106.list_removerange.dart",
    "107.list_shuffle.dart",
    "108.list_remove_at.dart",
    "109.list_insert.dart",
    "110.list_add_all.dart",
    "111.read_super_field.dart",
    "112.write_super_field.dart",
    "113.global_preincrement.dart",
    "114.global_predecrement.dart",
    "115.global_increment.dart",
    "116.global_decrement.dart",
    "117.initializer_list.dart",
    "118.typed_cons_params.dart",
    "119.multiline_comment.dart",
    "120.getter.dart",
    "121.getter2.dart",
    "122.list_get_length.dart",
];


pub const FAILTESTS: &'static [&'static str] = &[
    "0.cross_function_leak.dart",
    "1.double_declaration.dart",
    "2.forgotten_paramlist.dart",
    "3.plus_is_not_prefix.dart",
    "4.var_not_declared.dart",
    "5.var_not_declared2.dart",
    "6.extraneous_comma.dart",
    "7.illegal_operand_pluss.dart",
    "8.illegal_operand_minus.dart",
    "9.topvar_double_decl.dart",
    "10.non_transitive_imports/main.dart",
    "11.topvar_cycle/main.dart",
    "12.const_topvar_set.dart",
    "13.const_calls_func.dart",
    "14.topvar_stack_leak.dart",
    "15.wrong_owner.dart",
    "16.wrong_owner2.dart",
];


pub fn get_failfilepath(s: String, paths: &Dirs) -> String {

    return match s.parse::<usize>() {
        Ok(i) => {
            format!("{}/{}", paths.failtestdir(), FAILTESTS[i])
        },
        Err(_e) => {
            format!("{}/{}", paths.failtestdir(), s)
        },
    };
}


pub fn get_filepath(s: String, paths: &Dirs) -> String {

    return match s.parse::<usize>() {
        Ok(i) => {
            format!("{}/{}", paths.testdir(), TESTS[i])
        },
        Err(_e) => {
            format!("{}/{}", paths.testdir(), s)
        },
    };
}
